### ISSUE TITLE
Couldn't get it to work for a simple express server

### ISSUE THREAD

**Issue by shivkanthb** [JamesKyburz/aws-lambda-http-server#33]
Hi! 

Thank you for building this package (and the dep packages). 

I tried this just like your demo but with a simple express server and serverless but however I noticed:

1. `sls deploy` deploys to api gateaway as a REST Api (version 1)
2. I manually created a http api and pointed to the lambda function created but I get these in the logs when I try to hit the endpoint
```

2020-11-29T14:38:47.272Z	a49f0436-6698-4feb-8b18-f70602c6700e	ERROR	TypeError: Cannot read property 'toLowerCase' of undefined    at Route._handles_method (/var/task/node_modules/express/lib/router/route.js:63:21)    at next (/var/task/node_modules/express/lib/router/index.js:244:30)    at expressInit (/var/task/node_modules/express/lib/middleware/init.js:40:5)    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)    at trim_prefix (/var/task/node_modules/express/lib/router/index.js:317:13)    at /var/task/node_modules/express/lib/router/index.js:284:7    at Function.process_params (/var/task/node_modules/express/lib/router/index.js:335:12)    at next (/var/task/node_modules/express/lib/router/index.js:275:10)    at query (/var/task/node_modules/express/lib/middleware/query.js:45:5)    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5) | 2020-11-29T14:38:47.272Z a49f0436-6698-4feb-8b18-f70602c6700e ERROR TypeError: Cannot read property 'toLowerCase' of undefined at Route._handles_method (/var/task/node_modules/express/lib/router/route.js:63:21) at next (/var/task/node_modules/express/lib/router/index.js:244:30) at expressInit (/var/task/node_modules/express/lib/middleware/init.js:40:5) at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/var/task/node_modules/express/lib/router/index.js:317:13) at /var/task/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/var/task/node_modules/express/lib/router/index.js:335:12) at next (/var/task/node_modules/express/lib/router/index.js:275:10) at query (/var/task/node_modules/express/lib/middleware/query.js:45:5) at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
-- | --

```

Am I missing anything / doing something incorrectly?

**Comment by JamesKyburz** [comment]
How is the function invoked? The event payload should have  `httpMethod` set when invoked by http.

**Comment by shivkanthb** [comment]
Once deployed I just hit the url directly on the browser. That should automatically set the method to GET right?

**Comment by JamesKyburz** [comment]
Could you post your lambda code?

**Comment by shivkanthb** [comment]
Sure!

server.js
```
const express = require('express');
 
const app = express();

app.get('/', (req, res) => {
  return res.json({ message: 'Hello world!'});
})
app.get('/hello', (req, res) => {
  return res.send('world');
});
 
app.listen(3000, () =>
  console.log('Example app listening on port 3000!'),
);
```

and lambda.js
```
exports.proxy = require('aws-lambda-http-server')
require('./server.js')
```

serverless.yml
```
service: xpresslamb
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
functions:
  proxy:
    handler: lambda.proxy
    events:
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: ''
          method: any
```

**Comment by JamesKyburz** [comment]
It seems to have been an issue with supporting both api gateway 1 and 2.

When I last tested it version was sent as 1.0 in api gateway 1 (now it is missing - this caused my validation to fail).

I have published version 0.2.3 with a fix, if no version exists in the payload the version defaults to 1.0.

**Comment by JamesKyburz** [comment]
@shivkanthb could you please check it now works for you with the latest version?

**Comment by shivkanthb** [comment]
Hey @JamesKyburz,  Thank you for the quick fix! Did an npm update and `sls deploy` and its working great now for the REST API. 

Deployed another one to use the HTTP api with the following serverless.yml file
```
service: xpresslambhttp
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
functions:
  proxy:
    handler: lambda.proxy
    events:
      - httpApi: "*"
```

But I get the following error
```
2020-12-14T06:52:36.005Z	54cc8395-bc9f-4553-a426-e6499f6086fb	ERROR	TypeError: Cannot read property 'toLowerCase' of undefined
    at Route._handles_method (/var/task/node_modules/express/lib/router/route.js:63:21)
    at next (/var/task/node_modules/express/lib/router/index.js:244:30)
    at expressInit (/var/task/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/task/node_modules/express/lib/router/index.js:317:13)
    at /var/task/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/task/node_modules/express/lib/router/index.js:335:12)
    at next (/var/task/node_modules/express/lib/router/index.js:275:10)
    at query (/var/task/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
2020-12-14T06:52:36.005Z 54cc8395-bc9f-4553-a426-e6499f6086fb ERROR TypeError: Cannot read property 'toLowerCase' of undefined at Route._handles_method (/var/task/node_modules/express/lib/router/route.js:63:21) at next (/var/task/node_modules/express/lib/router/index.js:244:30) at expressInit (/var/task/node_modules/express/lib/middleware/init.js:40:5) at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/var/task/node_modules/express/lib/router/index.js:317:13) at /var/task/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/var/task/node_modules/express/lib/router/index.js:335:12) at next (/var/task/node_modules/express/lib/router/index.js:275:10) at query (/var/task/node_modules/express/lib/middleware/query.js:45:5) at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
```

Im invoking again by just hitting the endpoint on the browser! Anything I'm missing here?

**Comment by JamesKyburz** [comment]
I can't find when but I think the payload of the api gateway v2 request changed since I last tested it.

In any case please update again and your httpAPI endpoint should now work

**Comment by shivkanthb** [comment]
Thanks James! Updated and works now! Really appreciate it :)

**Comment by JamesKyburz** [comment]
Great stufff! Thanks for identifying the problem.
